### ISSUE TITLE
Integrate new symfony/dotenv functionnality

### ISSUE THREAD

**Issue by wtfred** [helhum/dotenv-connector#17]
Hello Helmut,

Would it be possible to replace in https://github.com/helhum/dotenv-connector/blob/master/res/PHP/dotenv-include.php.tmpl#L4 `load` with `loadEnv` so we can enjoy the new possibilities of the symfony component? 

Thanks for reading!

**Extract from https://symfony.com/doc/4.4/components/dotenv.html#usage:**

The Dotenv component will then look for the correct .env file to load in the following order whereas the files loaded later override the variables defined in previously loaded files :

1. If .env exists, it is loaded first. In case there's no .env file but a .env.dist, this one will be loaded instead.
2. If one of the previously mentioned files contains the APP_ENV variable, the variable is populated and used to load environment-specific files hereafter. If APP_ENV is not defined in either of the previously mentioned files, dev is assumed for APP_ENV and populated by default.
3. If there's a .env.local representing general local environment variables it's loaded now.
4. If there's a .env.$env.local file, this one is loaded. Otherwise, it falls back to .env.$env.

This might look complicated at first glance but it gives you the opportunity to commit multiple environment-specific files that can then be adjusted to your local environment. Given you commit .env, .env.test and .env.dev to represent different configuration settings for your environments, each of them can be adjusted by using .env.local, .env.test.local and .env.dev.local respectively.

**Comment by helhum** [comment]
Thanks for your report. See #15 for a discussion on such change.
Just changing the API call is no option, as it would be a breaking change and might also not be desired for all consumers of this package.

It would need to be configurable somehow.

> This might look complicated at first glance

It still looks complicated at second glance :)

> each of them can be adjusted by using .env.local, .env.test.local and .env.dev.local respectively

The fact that you missed, that `.env.test.local` [won't work by design](https://github.com/symfony/dotenv/blob/2ecb841be2b04c0f84d1f5c7000be474c4bf095f/Dotenv.php#L89) is a good indicator for me, that it in fact **is** too complicated.
But it is just my personal take and does not mean I would block a feature allowing to *optionally* use `loadEnv` instead of `load`.

Could you do a pull request implementing this?

**Comment by wtfred** [comment]
> Could you do a pull request implementing this?
Ok, i'll try to make that in the next few days :)
